# Generated by Django 4.1.8 on 2023-05-03 07:36

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('provider_name', models.CharField(default='Anonymous', max_length=20)),
                ('profile_url', models.URLField()),
                ('job_title', models.CharField(default='Job Title', max_length=30)),
                ('job_description', models.TextField()),
                ('popularity', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'Job-Data',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='jobs_applied',
            field=models.IntegerField(default=0),
        ),
    ]
