# Generated by Django 4.1.8 on 2023-05-08 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_jobdata_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobdata',
            name='provider_name',
            field=models.CharField(default='Anonymous', max_length=120),
        ),
    ]
